#!/usr/bin/perl -T

use strict;
use warnings;
use CGI;
use CGI::Session;

my $cgi = new CGI;

my $user_dir = '/tmp/session/user';
-d $user_dir    or mkdir $user_dir  or die "mkdir $user_dir: $!\n";

my $session = new CGI::Session(undef, $cgi, {Directory=>'/tmp/session'});

my $remote_user = $cgi->remote_user or die;
$remote_user =~ /^(.*)$/    and $remote_user = $1;

my $user_file ="$user_dir/$remote_user"; 
if (! -f $user_file) {
    open my $fh, '>', $user_file    or die "$user_file: $!\n";
    print $fh $session->id();
    close $fh;
}
else {
    open my $fh, '<', $user_file    or die "$user_file: $!\n";
    my $id = <$fh>;
    close $fh;
    $session->delete();
    $session = new CGI::Session(undef, $id, {Directory=>'/tmp/session'});
}

print $session->header(-status=>302, -location=>'./');
